prevent crash with angelica caused by OPENGL debug
prevent this :
```

java.lang.IllegalAccessError: tried to access method com.gtnewhorizons.angelica.glsm.GLStateManager.glGetBoolean(ILjava/nio/ByteBuffer;)V from class makamys.coretweaks.util.OpenGLDebugging
	at makamys.coretweaks.util.OpenGLDebugging.getPropertyAsString(OpenGLDebugging.java:159)
	at makamys.coretweaks.util.OpenGLDebugging.dumpState(OpenGLDebugging.java:110)
	at makamys.coretweaks.util.OpenGLDebugging.dumpState(OpenGLDebugging.java:105)
	at makamys.coretweaks.util.GLUtil.resetState(GLUtil.java:18)
	at makamys.coretweaks.tweak.crashhandler.CrashHandler.resetState(CrashHandler.java:40)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:7536)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```